name: Maven

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [ '8', '11', '17', '22' ]
        dist: [ 'zulu' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.dist }}
          cache: 'maven'

      - name: Maven Package
        env:
          MAVEN_OPTS: -Dmaven.artifact.threads=64
        run: mvn -V package --no-transfer-progress
